name: Render Jupyter Notebook

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install nbformat
        shell: bash
      - name: Convert notebook
        run: |
          nbformat --validate --interactive --stdin "your_notebook.ipynb" | nbformat --to html > "output.html"
        shell: bash
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Updated notebook HTML"
          branch: "gh-pages"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: "./"
          branch: "gh-pages"
